# Generated by Django 4.2.15 on 2024-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(max_length=20)),
                ('Department', models.CharField(max_length=100)),
                ('Doctor', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Message', models.TextField(max_length=1000)),
            ],
        ),
    ]
